[workspace]
resolver = "3"

members = [
    "core",
    "xtask",
    "crates/icalendar_txt",
    "crates/todo_txt",
    "crates/sync",
    "crates/cli",
]
default-members = [ "crates/cli" ]

[workspace.package]
version = "0.1.0"
authors = [ "Sandorex" ]
description = "Calendar notes and todos all in one, synced using pure git"
repository = "https://github.com/sandorex/calnoto"
